setwd("C:\\easy_r")

library(KoNLP)
library(wordcloud)
library(stringr)
buildDictionary()
txt<-readLines("noh.txt")
nouns<-sapply(txt,extractNoun,USE.NAMES=F)
head(unlist(nouns),30)
nouns <- filter(function(x) {nchar(x)>=},unlist(nouns))
write(unlist(nouns),'noh_2.txt')
rev <-read.table('noh_2.txt')
nrow(rev)
wordcount<-table(rev)
head(sort(wordcount,decreasing=T),30)
library(RColorBrewer)
palete<-brewer.pal(9,"Set1")
wordcloud(names(wordcount),freq=wordcount,scale=c(5,0.1),rot.per=0.25,min.freq=1,random.order=F,random.color=T,colors=palete)
legend(0.3,1,"故 노무현 대통령님 연설문 분석 ",cex=0.8,fill=NA,bg="white",text.col="red",text.font=2,box.col="red")